sdf_chamfer: {
      "mesh_outer_hair": "./implicit-hair-data/data/nphm/028/28_mesh.obj",
      "mesh_outer_hair_remeshed": "./implicit-hair-data/data/nphm/028/28_mesh_remeshed.obj",
      "num_points": 60000,
      }
      
textured_strands: {
      "path_to_mesh": "./implicit-hair-data/data/nphm/028/registration.ply",
      "decoder_checkpoint_path": "./pretrained_models/strand_prior/strand_ckpt.pth",
      "num_strands": 1900,
      "max_num_strands": 100000,
      "texture_size": 256,
      "geometry_descriptor_size": 64,
      "appearance_descriptor_size": 16,
      # "cut_scalp": "./implicit-hair-data/data/nphm/039/cut_scalp_verts.pickle"
  }

diffusion_prior: {
      "use_diffusion": true,
      "start_denoise": 1,
      # "diffuse_mask": "./implicit-hair-data/data/nphm/039/dif_mask.png",
      "diffuse_bs": 32,
      "dif_path": "./pretrained_models/diffusion_prior/dif_ckpt.pth",  
       model: {
          "type": "image_v1",
          "input_channels": 64,
          "input_size": [32, 32],
          "patch_size": 1,
          "mapping_out": 256,
          "depths": [2, 4, 4],
          "channels": [128, 256, 512],
          "mapping_cond_dim": 0,
          "unet_cond_dim": 0,
          "cross_cond_dim": 0,
          "cross_attn_depths": None,
          "self_attn_depths": [false, false, false],
          "has_variance": true,
          "dropout_rate": 0.05,
          "skip_stages": 0,
          "augment_wrapper": false,
          "augment_prob": 0.12,
          "sigma_data": 0.5,
          "sigma_min": 0.02,
          "sigma_max": 40,
          "sigma_sample_density": {
              "type": "lognormal",
                "mean": -1.2,
                "std": 1.2
            }
      }
  }
  
render: {
    "use_render": False,
    "image_size": 512,
    "feat_size": 16,
    "mesh_path": "./implicit-hair-data/data/monocular/person_0/head_prior.obj",
    "num_strands": 1900,
    "strands_len": 99,
    "logging_freq": 500,
    "out_channels": 3,
    "use_orients_cond": true,
    "use_silh": true,
 }

general: {
    "lr": 0.001,
    "starting_rendering_iter": 1,
    "gamma": 0.5,
    "milestones": [40000, 60000, 80000],
    "orientation_path": './implicit-hair-data/data/nphm/028/28_orients_orig_crest.ply',
    "sdf_path": './implicit-hair-data/data/nphm/028/ckpt_040000.pth'
  }
  
loss_factors: {
    "volume": 1.,
    "orient": 0.01,
    "chamfer": 1.,
    "raster_silh": 0.00001,
    "raster_l1": 0.001,
    "raster_alpha": 0.0,
    "L_diff": 0.001,
  }

udf_network: {
    "d_out": 1,
    "d_in": 3,
    "d_hidden": 256,
    "n_layers": 8,
    "skip_in": [4],
    "multires": 0,
    "bias": 0.5,
    "scale": 1.0,
    "geometric_init": True,
    "weight_norm": True,
  }

nsh_network: {
  "latent_size": 0,
  "in_dim": 3,
  "decoder_hidden_dim": 256,
  "nl": "sine",
  "decoder_n_hidden_layers": 4,
  "init_type": "siren",
  "sphere_init_params": [1.6, 0.1],
  "udf": False,
  "vae": False,
}